assistants:
  gpt4:
    name: chatgpt
    api_key: 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
    model: gpt-4-turbo-preview